const CHANNEL_SUB = 'CHANNEL_SUB';
const USER_SUB = 'USER_SUB';
const MESSAGE_ADDED = 'MESSAGE_ADDED';

const DEFAULT_SERVER_ID = 'welcome';

module.exports = {
  CHANNEL_SUB,
  USER_SUB,
  MESSAGE_ADDED,
  DEFAULT_SERVER_ID,
};
